---
# handlers file for cowrie honeypot
- name: Restart cowrie
  ansible.builtin.systemd:
    name: cowrie
    daemon_reload: yes
    state: restarted
  listen: "Restart cowrie"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  listen: "Reload systemd"
...
