---
- block:

  - name: Copy Pickle Filesystem to Remote System(s)
    ansible.builtin.copy:
      src: "{{ cowrie.custom_fs }}"
      dest: "{{ honeypot.hmdir }}/{{ cowrie.dir }}/share/cowrie/fs.pickle"
      mode: 0644

    when:
        - cowrie.custom_fs is defined  

    become: true
    become_user: "{{ honeypot.user }}"
...
